language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install python-dev libssl-dev libffi-dev
  - pip install -U pyopenssl==0.13.1 pyasn1 ndg-httpsclient
  - pip install requests[security]
  - pip install --user cpp-coveralls

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - git clone https://github.com/google/googletest.git gtest2
  - mv gtest2/googletest gtest
  - g++ -isystem gtest/include -Igtest -std=c++11 -pthread -c gtest/src/gtest-all.cc
  - ar -rv libgtest.a gtest-all.o

script:
- cd src
- g++ -g main.cpp uci.cpp board.cpp utilities.cpp timing.cpp engine.cpp mover.cpp evaluation.cpp -std=c++11 -pthread -o DeepPigeon
- cd ..
- g++ -isystem gtest/include src/board.cpp -std=c++11 -pthread tests/board_test.cpp libgtest.a -o dist/DeepPigeon_test

after_success:
  - coveralls --skip-ssl-verify --root . -E ".*dist.*" -E ".*bib.*" -E ".*gtest.*" -E ".*CMakeFiles.*"

branches:
  only:
  - master